include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_function_literals_in_foreach_calls: false
    overridden_fields: false
